// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiskAssessment.Models;

namespace RiskAssessment.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20210925013647_CurrentValueTableCreation")]
    partial class CurrentValueTableCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RiskAssessment.Models.Entities.CollateralRisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAssessed")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanId")
                        .HasColumnType("int");

                    b.Property<int>("RiskPercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("collateralRisks");
                });

            modelBuilder.Entity("RiskAssessment.Models.Entities.CurrentValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GoldUnitValue")
                        .HasColumnType("int");

                    b.Property<int>("LandUnitValue")
                        .HasColumnType("int");

                    b.Property<int>("OtherAssetUnitValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("currentValues");
                });
#pragma warning restore 612, 618
        }
    }
}
